### ISSUE TITLE
VPN connected successfully, but cannot access internal resources via snx-rs with SAML

### ISSUE THREAD

**Issue by PauloJhonny** [ancwrd1/snx-rs#91]
Hi! I'm using snx-rs on Linux to connect to my organization's VPN using SAML. The connection is successfully established using the following command:

```
sudo ./target/release/snx-rs \
  -s VPN_URL \
  -o vpn_SAML_Google \
  --ignore-server-cert true \
  --no-dns true \
  --log-level debug \
  -e ipsec
```

Authentication works fine and the VPN connection is established without any visible errors (Connected to VPN_URL via IPSec, press Ctrl-C to exit.). However, after connecting, I cannot access internal URLs or SSH into hosts that should only be accessible through the VPN.

If I omit `--no-dns` or set `--no-dns false`, I get the following error:

```
Error: Domain not valid: .xxx.xx.xx
Failed to set domain configuration: Invalid argument
```

If I omit `--ignore-server-cert` or set it to false, I get

```
Error: error sending request for url (https://VPN_URL/clients/)

Caused by:
    0: client error (Connect)
    1: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1913: (self signed certificate in certificate chain)
    2: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1913:
```

Could you help me to solve this problem, please?

Thank you.

**Comment by ancwrd1** [comment]
I think your VPN server returns back invalid DNS information. Could you can check it with the debug logs, there will be an entry similar to this:

```
Configuring resolver: ResolverConfig { search_domains: ["xxx", "yyy"], dns_servers: [10.0.0.99, 10.0.0.101] }
```
Check if anything there is may be in incorrect format.

**Comment by ancwrd1** [comment]
If you don't see this entry, try enabling trace-level logs and look up for this:

```
2025-04-22T18:04:05.049131Z DEBUG isakmp::ikev1::service: Begin sending OM request
2025-04-22T18:04:05.049183Z TRACE isakmp::transport::tcpt: Sending ISAKMP message: IsakmpMessage {
    ... not important ...
}
2025-04-22T18:04:05.113541Z TRACE isakmp::payload: Parsing payload: type=Hash, size=32, next=Attributes
2025-04-22T18:04:05.113573Z TRACE isakmp::payload: Parsing payload: type=Attributes, size=128, next=None
2025-04-22T18:04:05.113588Z TRACE isakmp::transport::tcpt: Received ISAKMP message: IsakmpMessage {
    ... not important ...
        Attributes(
            AttributesPayload {
                attributes_payload_type: Reply,
                identifier: 11992,
                attributes: [
                    DataAttribute {
                        attribute_type: 1,
                        value: Long(
                            b"\n\0\x1d\x1f",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 2,
                        value: Long(
                            b"\xff\xff\xfc\0",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 3,
                        value: Long(
                            b"\n\0\0c",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 3,
                        value: Long(
                            b"\n\0\0e",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 5,
                        value: Long(
                            b"\0\0p{",
                        ),
                    },
                    DataAttribute {
                        attribute_type: 16387,
                        value: Long(
                            b"xxx,yyy",
                        ),
                    },
                ],
            },
        ),
    ],
}
```

Those DataAttribute entries contain IP, DNS and and subnet values. Type 1 = IPv4, type 2 = netmask, type 3 = DNS server, type 16387 = search domains.

to check IP addresses, use Python one-liner: `print('.'.join(str(b) for b in b"\n\0\x1d\x1f"))`

**Comment by PauloJhonny** [comment]
@ancwrd1, When the connection is established, this appears in the log. Even though I try to access internal URLs that can only be accessed with a VPN, nothing else appears in the logs.

```
sudo ./target/release/snx-rs -s VPN_URL -o vpn_SAML_Google --ignore-server-cert true --no-dns true --log-level debug -e ipsec
2025-04-22T18:08:30.629122Z DEBUG snx_rs: >>> Starting snx-rs client version 3.1.2
2025-04-22T18:08:30.629134Z DEBUG snx_rs: Running in standalone mode
2025-04-22T18:08:30.629248Z  WARN snxcore::ccc: Disabling all certificate checks!!!
2025-04-22T18:08:30.653506Z DEBUG hyper_util::client::legacy::connect::http: connecting to 200.150.65.50:443
2025-04-22T18:08:30.699304Z DEBUG hyper_util::client::legacy::connect::http: connected to 200.150.65.50:443
2025-04-22T18:08:30.881321Z DEBUG snxcore::tunnel::ipsec::natt: Sending NAT-T probe to 200.150.65.50:4500
2025-04-22T18:08:30.925537Z DEBUG snxcore::tunnel::ipsec::natt: Received NAT-T reply from 200.150.65.50:4500: srcport: 4500, dstport: 4500, hash: 4ae71336e44bf9bf79d2752e234818a5
2025-04-22T18:08:30.925616Z DEBUG snxcore::tunnel::ipsec::connector: Using ESP transport: UDP
2025-04-22T18:08:30.927003Z DEBUG snxcore::tunnel::ipsec::connector: Using IKE transport: UDP
2025-04-22T18:08:30.935903Z DEBUG isakmp::ikev1::service: Begin SA proposal
2025-04-22T18:08:30.936060Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 736, to: 200.150.65.50:4500
2025-04-22T18:08:30.979474Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 272
2025-04-22T18:08:30.979658Z DEBUG isakmp::ikev1::service: Negotiated SA hash algorithm: Sha
2025-04-22T18:08:30.979698Z DEBUG isakmp::ikev1::service: Negotiated SA encryption algorithm: AesCbc
2025-04-22T18:08:30.979758Z DEBUG isakmp::ikev1::service: Negotiated SA key length: 32
2025-04-22T18:08:30.979777Z DEBUG isakmp::ikev1::service: Negotiated SA group: Oakley2
2025-04-22T18:08:30.979806Z DEBUG isakmp::ikev1::service: Negotiated SA lifetime: 28800
2025-04-22T18:08:30.981175Z DEBUG isakmp::ikev1::service: End SA proposal
2025-04-22T18:08:30.981197Z DEBUG isakmp::ikev1::service: Begin key exchange
2025-04-22T18:08:30.981269Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 244, to: 200.150.65.50:4500
2025-04-22T18:08:31.030725Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 391
2025-04-22T18:08:31.032211Z DEBUG isakmp::ikev1::service: End key exchange
2025-04-22T18:08:31.032538Z DEBUG isakmp::ikev1::service: Begin identity protection
2025-04-22T18:08:31.032675Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 396, to: 200.150.65.50:4500
2025-04-22T18:08:31.089955Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 1920
2025-04-22T18:08:31.090148Z DEBUG isakmp::ikev1::service: Trusted server fingerprint: PUG TROY EVA OF AID MEND TAKE ALTO OHIO CUR KENT KATE
2025-04-22T18:08:31.090368Z DEBUG isakmp::ikev1::service: Fingerprint for: organizationName = "sms..a4ohga",commonName = "checkpoint-cls VPN Certificate": PUG TROY EVA OF AID MEND TAKE ALTO OHIO CUR KENT KATE
2025-04-22T18:08:31.090395Z DEBUG isakmp::ikev1::service: Internal IPSec certificate validation succeeded
2025-04-22T18:08:31.090451Z DEBUG isakmp::ikev1::service: IP address from ID payload: 10.56.250.1
2025-04-22T18:08:31.090734Z DEBUG isakmp::ikev1::service: ID payload signature verification succeeded!
2025-04-22T18:08:31.090756Z DEBUG isakmp::ikev1::service: Awaiting authentication factors
2025-04-22T18:08:31.190537Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 1920
2025-04-22T18:08:31.291390Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 1920
2025-04-22T18:08:31.588223Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 944
2025-04-22T18:08:31.588411Z DEBUG isakmp::ikev1::service: Attributes message ID: 3d7ca7bc
2025-04-22T18:08:31.588455Z DEBUG isakmp::ikev1::service: End identity protection
2025-04-22T18:08:31.588502Z DEBUG snxcore::tunnel::ipsec::connector: No status in reply, requested challenge for: UserPassword
2025-04-22T18:08:31.588538Z DEBUG snxcore::tunnel::ipsec::connector: Challenge msg: https://VPN_URL/saml-vpn/spPortal/ServiceProviderTabs?realm=vpn_SAML_Google&session=5hakqo4tir3oxuh
2025-04-22T18:08:31.588761Z DEBUG snxcore::tunnel::ipsec::connector: Challenge ID: CPSC_SP_URL
2025-04-22T18:08:31.588786Z DEBUG snxcore::tunnel::ipsec::connector: Challenge prompt: https://VPN_URL/saml-vpn/spPortal/ServiceProviderTabs?realm=vpn_SAML_Google&session=5hakqo4tir3oxuh
For SAML authentication open the following URL in your browser:
https://VPN_URL/saml-vpn/spPortal/ServiceProviderTabs?realm=vpn_SAML_Google&session=5hakqo4tir3oxuh
2025-04-22T18:08:33.588149Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 944
2025-04-22T18:08:35.588376Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 944
2025-04-22T18:08:37.588707Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 944
2025-04-22T18:08:39.588840Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 944
2025-04-22T18:08:41.586306Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 944
2025-04-22T18:08:43.589196Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 944
2025-04-22T18:08:46.317930Z DEBUG isakmp::ikev1::service: Sending auth attribute: UserPassword, timeout: Some(120) seconds
2025-04-22T18:08:46.318027Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 140, to: 200.150.65.50:4500
2025-04-22T18:08:46.370786Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 704
2025-04-22T18:08:46.370911Z DEBUG isakmp::ikev1::service: Message ID: 3d7ca7bc
2025-04-22T18:08:46.370922Z DEBUG isakmp::ikev1::service: Response message ID: 3d7ca7bc
2025-04-22T18:08:46.370949Z DEBUG snxcore::tunnel::ipsec::connector: IPSec authentication succeeded
2025-04-22T18:08:46.370955Z DEBUG isakmp::ikev1::service: Sending ACK response
2025-04-22T18:08:46.371041Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 76, to: 200.150.65.50:4500
2025-04-22T18:08:46.371106Z DEBUG isakmp::ikev1::service: Begin sending OM request
2025-04-22T18:08:46.371172Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 124, to: 200.150.65.50:4500
2025-04-22T18:08:46.414380Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 176
2025-04-22T18:08:46.414578Z DEBUG isakmp::ikev1::service: End sending OM request
2025-04-22T18:08:46.414643Z DEBUG isakmp::ikev1::service: Begin ESP SA proposal
2025-04-22T18:08:46.414871Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 1148, to: 200.150.65.50:4500
2025-04-22T18:08:46.456874Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 176
2025-04-22T18:08:46.456981Z DEBUG isakmp::ikev1::service: Negotiated transform id: Esp3Des
2025-04-22T18:08:46.457005Z DEBUG isakmp::ikev1::service: Negotiated ESP auth algorithm: HmacSha96
2025-04-22T18:08:46.457009Z DEBUG isakmp::ikev1::service: Negotiated ESP key length: 24
2025-04-22T18:08:46.457023Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 60, to: 200.150.65.50:4500
2025-04-22T18:08:46.457068Z DEBUG isakmp::ikev1::service: End ESP SA proposal
2025-04-22T18:08:46.457078Z DEBUG snxcore::tunnel::ipsec::connector: ESP lifetime: 3600 seconds
2025-04-22T18:08:46.457109Z  WARN snxcore::ccc: Disabling all certificate checks!!!
2025-04-22T18:08:46.475370Z DEBUG hyper_util::client::legacy::connect::http: connecting to 200.150.65.50:443
2025-04-22T18:08:46.512154Z DEBUG hyper_util::client::legacy::connect::http: connected to 200.150.65.50:443
2025-04-22T18:08:46.515289Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 176
2025-04-22T18:08:46.616746Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 176
2025-04-22T18:08:46.671643Z DEBUG snxcore::tunnel::ipsec::imp::native: Resolved gateway address: 200.150.65.50, acquired internal address: 10.56.250.1
2025-04-22T18:08:46.680022Z DEBUG snxcore::platform::linux::xfrm: Source IP: 192.168.0.121
2025-04-22T18:08:46.680054Z DEBUG snxcore::platform::linux::xfrm: Target IP: 200.150.65.50
2025-04-22T18:08:46.773460Z DEBUG snxcore::platform::linux::net: Setting up keepalive route through snx-xfrm
2025-04-22T18:08:46.777934Z DEBUG snxcore::platform::linux::net: Routes to add: {10.22.9.239/32, 104.19.223.79/32, 10.78.0.0/16, 200.142.14.148/32, 200.142.14.20/32, 10.56.0.0/16, 10.15.133.54/32, 10.15.54.247/32, 10.22.9.205/32, 10.65.0.0/16, 177.92.17.170/32, 200.189.114.63/32, 10.15.61.96/31, 104.16.155.36/32, 10.15.203.10/32, 200.150.64.210/32, 200.189.123.13/32, 10.22.9.203/32, 10.22.9.212/32, 200.189.123.160/32}
2025-04-22T18:08:46.777964Z DEBUG snxcore::platform::linux::net: Adding route: 10.22.9.239/32 via snx-xfrm
2025-04-22T18:08:46.779246Z DEBUG snxcore::platform::linux::net: Adding route: 104.19.223.79/32 via snx-xfrm
2025-04-22T18:08:46.780781Z DEBUG snxcore::platform::linux::net: Adding route: 10.78.0.0/16 via snx-xfrm
2025-04-22T18:08:46.784872Z DEBUG snxcore::platform::linux::net: Adding route: 200.142.14.148/32 via snx-xfrm
2025-04-22T18:08:46.786889Z DEBUG snxcore::platform::linux::net: Adding route: 200.142.14.20/32 via snx-xfrm
2025-04-22T18:08:46.788706Z DEBUG snxcore::platform::linux::net: Adding route: 10.56.0.0/16 via snx-xfrm
2025-04-22T18:08:46.791100Z DEBUG snxcore::platform::linux::net: Adding route: 10.15.133.54/32 via snx-xfrm
2025-04-22T18:08:46.792806Z DEBUG snxcore::platform::linux::net: Adding route: 10.15.54.247/32 via snx-xfrm
2025-04-22T18:08:46.794878Z DEBUG snxcore::platform::linux::net: Adding route: 10.22.9.205/32 via snx-xfrm
2025-04-22T18:08:46.797153Z DEBUG snxcore::platform::linux::net: Adding route: 10.65.0.0/16 via snx-xfrm
2025-04-22T18:08:46.798651Z DEBUG snxcore::platform::linux::net: Adding route: 177.92.17.170/32 via snx-xfrm
2025-04-22T18:08:46.800312Z DEBUG snxcore::platform::linux::net: Adding route: 200.189.114.63/32 via snx-xfrm
2025-04-22T18:08:46.801813Z DEBUG snxcore::platform::linux::net: Adding route: 10.15.61.96/31 via snx-xfrm
2025-04-22T18:08:46.803295Z DEBUG snxcore::platform::linux::net: Adding route: 104.16.155.36/32 via snx-xfrm
2025-04-22T18:08:46.804807Z DEBUG snxcore::platform::linux::net: Adding route: 10.15.203.10/32 via snx-xfrm
2025-04-22T18:08:46.807419Z DEBUG snxcore::platform::linux::net: Adding route: 200.150.64.210/32 via snx-xfrm
2025-04-22T18:08:46.808939Z DEBUG snxcore::platform::linux::net: Adding route: 200.189.123.13/32 via snx-xfrm
2025-04-22T18:08:46.811411Z DEBUG snxcore::platform::linux::net: Adding route: 10.22.9.203/32 via snx-xfrm
2025-04-22T18:08:46.812998Z DEBUG snxcore::platform::linux::net: Adding route: 10.22.9.212/32 via snx-xfrm
2025-04-22T18:08:46.815000Z DEBUG snxcore::platform::linux::net: Adding route: 200.189.123.160/32 via snx-xfrm
Connected to VPN_URL via IPSec, press Ctrl-C to exit.
2025-04-22T18:08:46.818365Z DEBUG snxcore::tunnel::ipsec::imp::native: Running IPSec tunnel
2025-04-22T18:08:46.818376Z DEBUG snxcore::tunnel::ipsec::natt: Listening for NAT-T packets on port 0.0.0.0:48250
2025-04-22T18:08:46.818483Z DEBUG snxcore::tunnel::ipsec::connector: Tunnel connected
2025-04-22T18:08:46.819410Z DEBUG snxcore::platform::linux::net: NetworkManager state changed to ConnectedGlobal
```

**Comment by ancwrd1** [comment]
I think you ran it with no-dns option, try enabling DNS and run with trace level logs.

**Comment by ancwrd1** [comment]
Most likely the received search domains are incorrect, please check and confirm.

**Comment by ancwrd1** [comment]
If this is the case and your search domains start with dots ".xxx.y.z", try the following patch in the code. Replace this line: https://github.com/ancwrd1/snx-rs/blob/e0ea116f5ba3e4a80fd91107eaa3d6e274ecb3ef/snxcore/src/platform/linux/resolver.rs#L25

with:

```rust
let search_domains = config.search_domains.iter().map(|s| s.trim_matches(|c: char| c.is_whitespace() || c == '.')).collect::<Vec<_>>();
```

**Comment by PauloJhonny** [comment]
@ancwrd1, If I run without `no-dns` option, the following error occurs:

```
2025-04-22T18:23:19.009127Z DEBUG snxcore::platform::linux::resolver: Detected resolver: SystemdResolved
2025-04-22T18:23:19.009144Z DEBUG snxcore::platform::linux::xfrm: Configuring resolver: ResolverConfig { search_domains: [".xxx.xx.br", ""], dns_servers: [ip1, ip2] }
2025-04-22T18:23:19.009174Z TRACE snxcore::util: Exec: "resolvectl" ["domain", "snx-xfrm", ".xxx.xx.br", ""]
2025-04-22T18:23:19.019212Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 80, to: 200.150.65.50:4500
2025-04-22T18:23:19.019226Z TRACE isakmp::transport::udp: Sending ISAKMP message: IsakmpMessage {
    cookie_i: 5332997860937495168,
    cookie_r: 11061243002727976460,
    version: 16,
    exchange_type: Informational,
    flags: IsakmpFlags(
        0x0,
    ),
    message_id: 973600497,
    payloads: [
        Delete(
            DeletePayload {
                doi: 0,
                protocol_id: Isakmp,
                spi_size: 16,
                spi: [
                    b"J\x02\x9dL\x91\x18\xf2\x80",
                    b"\x99\x81m\xe7\xef\xe0N\x0c",
                ],
            },
        ),
        Hash(
            BasicPayload {
                data: b"4g\xcce$n\xee\xf9\xf7\x9c\x8f\xd2\x0ewy\x7f\xcbTO\xf2",
            },
        ),
    ],
}
Error: Domain not valid: .xxx.xx.br
Failed to set domain configuration: Invalid argument
```

**Comment by ancwrd1** [comment]
I have pushed a patch for it, build and try again.

**Comment by PauloJhonny** [comment]
@ancwrd1, hi.

I was able to successfully connect to the VPN using SNX with SAML authentication. However, I’m still unable to access internal resources.

I’ve tried accessing internal URLs via browser and connecting to internal servers via SSH, but none of them are reachable. Maybe there is something wrong with the VPN configuration? Windows users have been able to reach thoses resources, but I’m still unable to do so on Linux.

`sudo ./target/release/snx-rs -s URL_VPN -o vpn_SAML_Google --ignore-server-cert true --log-level debug`

```
2025-04-23T15:32:20.623234Z DEBUG snx_rs: >>> Starting snx-rs client version 3.1.2
2025-04-23T15:32:20.623298Z DEBUG snx_rs: Running in standalone mode
2025-04-23T15:32:20.629016Z  WARN snxcore::ccc: Disabling all certificate checks!!!
2025-04-23T15:32:20.673184Z DEBUG hyper_util::client::legacy::connect::http: connecting to 200.150.64.210:443
2025-04-23T15:32:20.721582Z DEBUG hyper_util::client::legacy::connect::http: connected to 200.150.64.210:443
2025-04-23T15:32:20.904141Z DEBUG snxcore::tunnel::ipsec::natt: Sending NAT-T probe to 200.150.65.50
2025-04-23T15:32:20.952579Z DEBUG snxcore::tunnel::ipsec::natt: Received NAT-T reply from 200.150.65.50: srcport: 4500, dstport: 4500, hash: 4ae71336e44bf9bf79d2752e234818a5
2025-04-23T15:32:20.952660Z DEBUG snxcore::tunnel::ipsec::connector: Using ESP transport: UDP
2025-04-23T15:32:20.954238Z DEBUG snxcore::tunnel::ipsec::connector: Using IKE transport: UDP
2025-04-23T15:32:20.963818Z DEBUG isakmp::ikev1::service: Begin SA proposal
2025-04-23T15:32:20.964159Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 736, to: 200.150.65.50:500
2025-04-23T15:32:21.001757Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 268
2025-04-23T15:32:21.001864Z DEBUG isakmp::ikev1::service: Negotiated SA hash algorithm: Sha
2025-04-23T15:32:21.001883Z DEBUG isakmp::ikev1::service: Negotiated SA encryption algorithm: AesCbc
2025-04-23T15:32:21.001898Z DEBUG isakmp::ikev1::service: Negotiated SA key length: 32
2025-04-23T15:32:21.001912Z DEBUG isakmp::ikev1::service: Negotiated SA group: Oakley2
2025-04-23T15:32:21.002543Z DEBUG isakmp::ikev1::service: End SA proposal
2025-04-23T15:32:21.002563Z DEBUG isakmp::ikev1::service: Begin key exchange
2025-04-23T15:32:21.002594Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 244, to: 200.150.65.50:500
2025-04-23T15:32:21.044465Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 387
2025-04-23T15:32:21.045972Z DEBUG isakmp::ikev1::service: End key exchange
2025-04-23T15:32:21.046693Z DEBUG isakmp::ikev1::service: Begin identity protection
2025-04-23T15:32:21.046801Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 332, to: 200.150.65.50:500
2025-04-23T15:32:21.097930Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 1916
2025-04-23T15:32:21.098139Z DEBUG isakmp::ikev1::service: IP address from ID payload: 10.56.250.1
2025-04-23T15:32:21.098491Z DEBUG isakmp::ikev1::service: ID payload signature verification succeeded!
2025-04-23T15:32:21.098519Z DEBUG isakmp::ikev1::service: Awaiting authentication factors
2025-04-23T15:32:21.198166Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 1916
2025-04-23T15:32:21.297895Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 1916
2025-04-23T15:32:21.598783Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:21.598978Z DEBUG isakmp::ikev1::service: Attributes message ID: ccff343d
2025-04-23T15:32:21.599016Z DEBUG isakmp::ikev1::service: End identity protection
2025-04-23T15:32:21.599039Z DEBUG snxcore::tunnel::ipsec::connector: No status in reply, requested challenge for: UserPassword
2025-04-23T15:32:21.599058Z DEBUG snxcore::tunnel::ipsec::connector: Challenge msg: https://URL_VPN/saml-vpn/spPortal/ServiceProviderTabs?realm=vpn_SAML_Google&session=xwgedfx4ksgj4ud
2025-04-23T15:32:21.599231Z DEBUG snxcore::tunnel::ipsec::connector: Challenge ID: CPSC_SP_URL
2025-04-23T15:32:21.599247Z DEBUG snxcore::tunnel::ipsec::connector: Challenge prompt: https://URL_VPN/saml-vpn/spPortal/ServiceProviderTabs?realm=vpn_SAML_Google&session=xwgedfx4ksgj4ud
For SAML authentication open the following URL in your browser:
https://URL_VPN/saml-vpn/spPortal/ServiceProviderTabs?realm=vpn_SAML_Google&session=xwgedfx4ksgj4ud
2025-04-23T15:32:23.598671Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:25.598641Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:27.598603Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:29.598396Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:31.597128Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:33.598053Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:37.599143Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:41.598463Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:45.597723Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:49.597902Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:32:53.597632Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 940
2025-04-23T15:33:04.357722Z DEBUG isakmp::ikev1::service: Sending auth attribute: UserPassword, timeout: Some(120) seconds
2025-04-23T15:33:04.357792Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 140, to: 200.150.65.50:500
2025-04-23T15:33:04.416567Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 700
2025-04-23T15:33:04.416658Z DEBUG isakmp::ikev1::service: Message ID: ccff343d
2025-04-23T15:33:04.416667Z DEBUG isakmp::ikev1::service: Response message ID: ccff343d
2025-04-23T15:33:04.416671Z DEBUG snxcore::tunnel::ipsec::connector: IPSec authentication succeeded
2025-04-23T15:33:04.416674Z DEBUG isakmp::ikev1::service: Sending ACK response
2025-04-23T15:33:04.416696Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 76, to: 200.150.65.50:500
2025-04-23T15:33:04.416714Z DEBUG isakmp::ikev1::service: Begin sending OM request
2025-04-23T15:33:04.416731Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 124, to: 200.150.65.50:500
2025-04-23T15:33:04.465986Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 172
2025-04-23T15:33:04.466149Z DEBUG isakmp::ikev1::service: End sending OM request
2025-04-23T15:33:04.466213Z DEBUG isakmp::ikev1::service: Begin ESP SA proposal
2025-04-23T15:33:04.466590Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 1148, to: 200.150.65.50:500
2025-04-23T15:33:04.506415Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 172
2025-04-23T15:33:04.506597Z DEBUG isakmp::ikev1::service: Negotiated transform id: Esp3Des
2025-04-23T15:33:04.506652Z DEBUG isakmp::ikev1::service: Negotiated ESP auth algorithm: HmacSha96
2025-04-23T15:33:04.506664Z DEBUG isakmp::ikev1::service: Negotiated ESP key length: 24
2025-04-23T15:33:04.506700Z DEBUG isakmp::transport::udp: Sending ISAKMP message, len: 60, to: 200.150.65.50:500
2025-04-23T15:33:04.506855Z DEBUG isakmp::ikev1::service: End ESP SA proposal
2025-04-23T15:33:04.506885Z DEBUG snxcore::tunnel::ipsec::connector: ESP lifetime: 3600 seconds
2025-04-23T15:33:04.506965Z  WARN snxcore::ccc: Disabling all certificate checks!!!
2025-04-23T15:33:04.547146Z DEBUG hyper_util::client::legacy::connect::http: connecting to 200.150.65.50:443
2025-04-23T15:33:04.561843Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 172
2025-04-23T15:33:04.590425Z DEBUG hyper_util::client::legacy::connect::http: connected to 200.150.65.50:443
2025-04-23T15:33:04.674380Z DEBUG isakmp::transport::udp: Received ISAKMP message, len: 172
2025-04-23T15:33:04.761565Z DEBUG snxcore::tunnel::ipsec::imp::native: Resolved gateway address: 200.150.64.210, acquired internal address: 10.56.250.1
2025-04-23T15:33:04.770472Z DEBUG snxcore::platform::linux::xfrm: Source IP: 192.168.0.121
2025-04-23T15:33:04.770505Z DEBUG snxcore::platform::linux::xfrm: Target IP: 200.150.64.210
2025-04-23T15:33:04.786453Z DEBUG snxcore::platform::linux::resolver: Detected resolver: SystemdResolved
2025-04-23T15:33:04.786495Z DEBUG snxcore::platform::linux::xfrm: Configuring resolver: ResolverConfig { search_domains: [".xxxx.yy.gg", ""], dns_servers: [10.56.1.151, 10.56.1.152] }
2025-04-23T15:33:04.946580Z DEBUG snxcore::platform::linux::net: Setting up keepalive route through snx-xfrm
2025-04-23T15:33:04.949446Z DEBUG snxcore::platform::linux::net: Routes to add: {10.56.0.0/16, 177.92.17.170/32, 200.150.65.50/32, 200.189.114.63/32, 10.65.0.0/16, 200.142.14.148/32, 10.15.133.54/32, 200.189.123.13/32, 10.15.54.247/32, 10.15.61.96/31, 200.189.123.160/32, 10.15.203.10/32, 10.22.9.212/32, 200.142.14.20/32, 10.22.9.239/32, 10.22.9.203/32, 10.78.0.0/16, 10.22.9.205/32, 104.19.223.79/32, 104.16.155.36/32}
2025-04-23T15:33:04.949465Z DEBUG snxcore::platform::linux::net: Adding route: 10.56.0.0/16 via snx-xfrm
2025-04-23T15:33:04.950526Z DEBUG snxcore::platform::linux::net: Adding route: 177.92.17.170/32 via snx-xfrm
2025-04-23T15:33:04.952121Z DEBUG snxcore::platform::linux::net: Adding route: 200.150.65.50/32 via snx-xfrm
2025-04-23T15:33:04.953367Z DEBUG snxcore::platform::linux::net: Adding route: 200.189.114.63/32 via snx-xfrm
2025-04-23T15:33:04.954667Z DEBUG snxcore::platform::linux::net: Adding route: 10.65.0.0/16 via snx-xfrm
2025-04-23T15:33:04.955949Z DEBUG snxcore::platform::linux::net: Adding route: 200.142.14.148/32 via snx-xfrm
2025-04-23T15:33:04.957187Z DEBUG snxcore::platform::linux::net: Adding route: 10.15.133.54/32 via snx-xfrm
2025-04-23T15:33:04.959035Z DEBUG snxcore::platform::linux::net: Adding route: 200.189.123.13/32 via snx-xfrm
2025-04-23T15:33:04.960347Z DEBUG snxcore::platform::linux::net: Adding route: 10.15.54.247/32 via snx-xfrm
2025-04-23T15:33:04.961620Z DEBUG snxcore::platform::linux::net: Adding route: 10.15.61.96/31 via snx-xfrm
2025-04-23T15:33:04.963015Z DEBUG snxcore::platform::linux::net: Adding route: 200.189.123.160/32 via snx-xfrm
2025-04-23T15:33:04.964427Z DEBUG snxcore::platform::linux::net: Adding route: 10.15.203.10/32 via snx-xfrm
2025-04-23T15:33:04.965781Z DEBUG snxcore::platform::linux::net: Adding route: 10.22.9.212/32 via snx-xfrm
2025-04-23T15:33:04.967762Z DEBUG snxcore::platform::linux::net: Adding route: 200.142.14.20/32 via snx-xfrm
2025-04-23T15:33:04.969037Z DEBUG snxcore::platform::linux::net: Adding route: 10.22.9.239/32 via snx-xfrm
2025-04-23T15:33:04.970509Z DEBUG snxcore::platform::linux::net: Adding route: 10.22.9.203/32 via snx-xfrm
2025-04-23T15:33:04.971920Z DEBUG snxcore::platform::linux::net: Adding route: 10.78.0.0/16 via snx-xfrm
2025-04-23T15:33:04.976377Z DEBUG snxcore::platform::linux::net: Adding route: 10.22.9.205/32 via snx-xfrm
2025-04-23T15:33:04.978281Z DEBUG snxcore::platform::linux::net: Adding route: 104.19.223.79/32 via snx-xfrm
2025-04-23T15:33:04.979656Z DEBUG snxcore::platform::linux::net: Adding route: 104.16.155.36/32 via snx-xfrm
2025-04-23T15:33:04.982339Z DEBUG snxcore::platform::linux::resolver: Detected resolver: SystemdResolved
2025-04-23T15:33:04.982354Z DEBUG snxcore::platform::linux::xfrm: Configuring resolver: ResolverConfig { search_domains: [".xxxx.yy.gg", ""], dns_servers: [10.56.1.151, 10.56.1.152] }
Connected to URL_VPN via IPSec, press Ctrl-C to exit.
2025-04-23T15:33:05.000982Z DEBUG snxcore::tunnel::ipsec::imp::native: Running IPSec tunnel
2025-04-23T15:33:05.000994Z DEBUG snxcore::tunnel::ipsec::natt: Listening for NAT-T packets on port 0.0.0.0:60515
2025-04-23T15:33:05.001122Z DEBUG snxcore::tunnel::ipsec::connector: Tunnel connected
2025-04-23T15:33:05.002469Z DEBUG snxcore::platform::linux::net: NetworkManager state changed to ConnectedGlobal
```

**Comment by ancwrd1** [comment]
run "resolvectl" without arguments and check if the configuration is correct and your search domains are correct. It should look something like that:

```
Link 4 (snx-xfrm)
    Current Scopes: DNS
         Protocols: -DefaultRoute +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.0.0.101
       DNS Servers: 10.0.0.99 10.0.0.101
        DNS Domain: my.company.local
     Default Route: no
```

Where `my.company.local` is the search domain, so you can access "somehost.my.company.local".
If it's incorrect there are two options which you can use: `--search-domains` to specify additional search domains, and `--ignore-search-domains` to ignore specific domains received from the server.

**Comment by ancwrd1** [comment]
If you cannot access internal resources also by IP addresses, then it could be something with the routing. Try specifying the "--default-route=true" option to route all traffic throuh the tunnel.

**Comment by PauloJhonny** [comment]
@ancwrd1, running `resolvectl`, I get the following result:

```
Link 11 (snx-xfrm)
      Current Scopes: DNS        
DefaultRoute setting: no         
       LLMNR setting: yes        
MulticastDNS setting: no         
  DNSOverTLS setting: no         
      DNSSEC setting: no         
    DNSSEC supported: no         
  Current DNS Server: 10.56.1.151
         DNS Servers: 10.56.1.151
                      10.56.1.152
          DNS Domain: xxxx.yy.gg
```

After this I ran:

`sudo ./target/release/snx-rs -s VPN_URL -o vpn_SAML_Google --ignore-server-cert true --log-level debug --search-domains ~xxxx.yy.gg,~xxxx.yyyy,~xxxx`

and IT WORKED!!!!

```
Link 12 (snx-xfrm)
      Current Scopes: DNS        
DefaultRoute setting: no         
       LLMNR setting: yes        
MulticastDNS setting: no         
  DNSOverTLS setting: no         
      DNSSEC setting: no         
    DNSSEC supported: no         
  Current DNS Server: 10.56.1.151
         DNS Servers: 10.56.1.151
                      10.56.1.152
          DNS Domain: ~xxxx.yy.gg
                      ~xxxx.yyyy,
                      ~xxxx
```

Now I can access internal resources via snx-rs with SAML.

Thank you so much for your help.

**Comment by ancwrd1** [comment]
Ah, there was probably a residual interface left from the failed connections previously. I will change the code to clean up properly in this case.
